strategy: ddp
benchmark: True
pretrained: False
sync_batchnorm: False
clip_grad: null
precision: 16
epochs: &epochs 300
# --------------------------------------
# Dataset parameters
# --------------------------------------
train_dataset:
  name: TemporalDataset
  params:
    data_path: &data_path data/itop_side.pkl
    split: [train, val]
val_dataset:
  name: TemporalDataset
  params:
    data_path: *data_path
    split: test
test_dataset:
  name: TemporalDataset
  params:
    data_path: data/itop_side.pkl
    split: test
# --------------------------------------
# Optimizer parameters
# --------------------------------------
optim_name: AdamW
optim_params:
  lr: 0.00001
  weight_decay: 0.00001
# --------------------------------------
# Learning rate scheduler parameters
# --------------------------------------
sched_name: LinearWarmupCosineAnnealingLR
sched_params:
  warmup_epochs: 20
  max_epochs: *epochs
  warmup_start_lr: 0.000001
  eta_min: 0.000001
# --------------------------------------
# Model parameters
# --------------------------------------
mode: train
model_name: P4Transformer
model_params:
  radius: 0.7
  nsamples: 32
  spatial_stride: 8
  temporal_kernel_size: 3
  temporal_stride: 1
  emb_relu: false
  dim: 1024
  depth: 5
  heads: 8
  dim_head: 128
  mlp_dim: 2048
  output_dim: 39
  features: 3
# --------------------------------------
# Loss parameters
# --------------------------------------
loss_name: MSELoss
loss_params: null
# weight for auxiliary losses
w_rec: 0.001
w_mem: 0.001
# --------------------------------------
# Augmentation parameters
# --------------------------------------
train_pipeline:
  - name: UniformSample
    params: 
      clip_len: 5
  - name: GetCentroid
    params: 
      centroid_type: 'dataset_median'
  - name: Normalize
    params:
      feat_scale: null
  - name: ToSimpleCOCO
    params: null
  - name: RemoveOutliers
    params: 
      outlier_type: 'box'
      radius: 1.5
  - name: AddNoisyPoints
    params:
      add_std: 0.2
      num_added: 32
      zero_centered: false
    prob: 0.5
  - name: AddPointsAroundJoint
    params:
      add_std: 0.2
      max_num2add: 3
      num_added: 32
    prob: 0.5
  - name: GenerateSegmentationGroundTruth
    params: null
  - name: DropPointsAtSegmentedJoints
    params:
      max_num2drop: 6
    prob: 0.5
  - name: RandomJitter
    params:
      jitter_std: 0.001
    prob: 0.5
  - name: RandomScale
    params:
      scale_min: 0.9
      scale_max: 1.1
    prob: 0.5
  - name: RandomRotate
    params:
      angle_min: -0.3141592653589793
      angle_max: 0.3141592653589793
    prob: 0.5
  - name: RandomTranslate
    params:
      translate_range: 0.01
    prob: 0.5
  - name: ReduceKeypointLen
    params:
      only_one: true
      keep_type: 'middle'
      frame_to_reduce: 0
  - name: Pad
    params:
      max_len: 1024
  - name: ToTensor
    params: null
val_pipeline: &val_pipeline
  - name: UniformSample
    params: 
      clip_len: 5
  - name: GetCentroid
    params: 
      centroid_type: 'dataset_median'
  - name: ToSimpleCOCO
    params: null
  - name: RemoveOutliers
    params: 
      outlier_type: 'box'
      radius: 2.0
  - name: Normalize
    params:
      feat_scale: null
  - name: ReduceKeypointLen
    params:
      only_one: true
      keep_type: 'middle'
      frame_to_reduce: 0
  - name: Pad
    params:
      max_len: 1024
  - name: ToTensor
    params: null
test_pipeline: *val_pipeline