strategy: ddp
benchmark: True
pretrained: False
sync_batchnorm: False
clip_grad: null
precision: 16
epochs: &epochs 100
# --------------------------------------
# Dataset parameters
# --------------------------------------
train_dataset:
  name: TemporalDataset
  params:
    data_path: &data_path data/lidarhuman26m.pkl
    split: [train, val]
val_dataset:
  name: TemporalDataset
  params:
    data_path: *data_path
    split: test
test_dataset:
  name: TemporalDataset
  params:
    data_path: *data_path #data/mmfi.pkl
    split: test
# --------------------------------------
# Optimizer parameters
# --------------------------------------
optim_name: AdamW
optim_params:
  lr: 0.0001
  weight_decay: 0.00001
# --------------------------------------
# Learning rate scheduler parameters
# --------------------------------------
sched_name: LinearWarmupCosineAnnealingLR
sched_params:
  warmup_epochs: 20
  max_epochs: *epochs
  warmup_start_lr: 0.00001
  eta_min: 0.00001
# --------------------------------------
# Model parameters
# --------------------------------------
mode: train
model_name: P4TransformerFlow
model_params:
  radius: 0.7
  nsamples: 32
  spatial_stride: 8
  temporal_kernel_size: 3
  temporal_stride: 1
  emb_relu: false
  dim: 1024
  depth: 5
  heads: 8
  dim_head: 128
  mlp_dim: 2048
  output_dim: 45
  features: 3
# --------------------------------------
# Loss parameters
# --------------------------------------
loss_name: MSELoss
loss_params: null
# weight for auxiliary losses
w_loc: 1.0
w_flow: 1.0
w_con: 0.001
# --------------------------------------
# Augmentation parameters
# --------------------------------------
train_pipeline:
  - name: UniformSample
    params:
      pad_type: 'end'
      clip_len: 5
  - name: GetCentroid
    params: 
      centroid_type: 'median'
  - name: Normalize
    params:
      feat_scale: null
  - name: ToITOP
    params: null
  - name: RemoveOutliers
    params: 
      outlier_type: 'box'
      radius: 1.25
  - name: AddNoisyPoints
    params:
      add_std: 1.0
      num_added: 32
      zero_centered: True
    prob: 0.5
  - name: GenerateSegmentationGroundTruth
    params: 
      padding: 0.25
  - name: ConvertToMMWavePointCloud
    params:
      dist_threshold: 0.01
      default_num_points: 32
  - name: RandomScale
    params:
      scale_min: 0.9
      scale_max: 1.1
    prob: 0.5
  - name: RandomRotate
    params:
      deg: true
      angle_min: -10
      angle_max: 10
    prob: 0.5
  - name: RandomTranslate
    params:
      translate_range: 0.01
    prob: 0.5
  - name: Pad
    params:
      max_len: 256
  - name: RandomJitter
    params:
      jitter_std: 0.02
    prob: 0.5
  - name: ToTensor
    params: null
val_pipeline: &val_pipeline
  - name: UniformSample
    params:
      pad_type: 'end'
      clip_len: 5
  - name: GetCentroid
    params: 
      centroid_type: 'median'
  - name: ToITOP
    params: null
  - name: Normalize
    params:
      feat_scale: null
  - name: RemoveOutliers
    params: 
      outlier_type: 'box'
      radius: 1.25
  - name: GenerateSegmentationGroundTruth
    params: 
      padding: 0.25
  - name: ConvertToMMWavePointCloud
    params:
      dist_threshold: 0.01
      default_num_points: 32
  # - name: DropPointsAtSegmentedJoints
  #   params:
  #     max_num2drop: 2
  - name: Pad
    params:
      max_len: 256
  - name: ToTensor
    params: null
test_pipeline: *val_pipeline
  # - name: UniformSample
  #   params:
  #     pad_type: 'end'
  #     clip_len: 5
  # - name: GetCentroid
  #   params: 
  #     centroid_type: 'zonly'
  # - name: ToITOP
  #   params: null
  # - name: Normalize
  #   params:
  #     feat_scale: null
  # - name: RemoveOutliers
  #   params: 
  #     outlier_type: 'box'
  #     radius: 1.25
  # - name: Pad
  #   params:
  #     max_len: 256
  # - name: ToTensor
  #   params: null