strategy: ddp
benchmark: True
pretrained: False
sync_batchnorm: False
clip_grad: null
precision: 16
epochs: 150
# --------------------------------------
# Dataset parameters
# --------------------------------------
data_pkl: mmfi.pkl
dataset_name: temporal
train_split: train_rdn_p3
val_split: val_rdn_p3
test_split: test_rdn_p3
# --------------------------------------
# Optimizer parameters
# --------------------------------------
optim_name: adamw
lr: 0.00001
weight_decay: 0.00001
momentum: 0.9
# --------------------------------------
# Learning rate scheduler parameters
# --------------------------------------
sched_name: cosine
warmup_lr: 0.000001
min_lr: 0.000001
warmup_epochs: 20
# --------------------------------------
# Model parameters
# --------------------------------------
model_name: ptr
stride: 1
epochs: 200
batch-size: 512
dropout: 0
learning-rate: 0.0001
lr_decay: 0.99
data_augmentation: False
number_of_frames: 5
num_joints: 13
num_input_dims: 64
in_chans: 3
embed_dim_ratio: 32
depth: 4
num_heads: 8
mlp_ratio: 2.0
qkv_bias: true
qk_scale: None
drop_path_rate: 0.1
# --------------------------------------
# Loss parameters
# --------------------------------------
loss_names: [mse]
gamma: 0.8
# --------------------------------------
# Augmentation parameters
# --------------------------------------
# pipeline
multi_frame: true
remove_outliers: true
random_jitter: true
flip: false
normalize: true
random_scale: true
random_rotate: true
random_translate: true
reduce_keypoint_len: true
pad: true
gen_seg_gt: false
to_simple_coco: true
# parameters
clip_len: 7
outlier_type: 'box'
num_neighbors: 3
std_multiplier: 1.0
radius: 2.0
min_neighbors: 2
centroid_type: 'zonly'
num_frames: 3
jitter_std: 0.001
jitter_prob: 0.5
left_idxs: [5,6,7,11,12,13,15,17]
right_idxs: [2,3,4,8,9,10,14,16]
flip_prob: 0.5
feat_scale: null
scale_min: 0.9
scale_max: 1.1
scale_prob: 0.5
angle_min: -3.141592653589793
angle_max: 3.141592653589793
rotate_prob: 0.5
translate_range: 0.05
translate_prob: 0.5
only_one: true
keep_type: 'middle'
frame_to_reduce: 0
max_len: 64
skeleton_type: 'mmfi'