strategy: ddp
benchmark: True
pretrained: False
sync_batchnorm: False
clip_grad: null
precision: 16
epochs: 150
# --------------------------------------
# Dataset parameters
# --------------------------------------
data_pkl: mmfi.pkl
dataset_name: temporal
train_split: train_rdn_p3
val_split: val_rdn_p3
test_split: test_rdn_p3
# --------------------------------------
# Optimizer parameters
# --------------------------------------
optim_name: adamw
lr: 0.00001
weight_decay: 0.00001
momentum: 0.9
# --------------------------------------
# Learning rate scheduler parameters
# --------------------------------------
sched_name: cosine
warmup_lr: 0.000001
min_lr: 0.000001
warmup_epochs: 20
# --------------------------------------
# Model parameters
# --------------------------------------
mode: train
model_name: p4tda3
radius: 0.7
nsamples: 32
spatial_stride: 8
temporal_kernel_size: 3
temporal_stride: 1
emb_relu: false
dim: 1024
depth: 5
heads: 8
dim_head: 128
mlp_dim: 2048
output_dim: 39
mem_size: 128
features: 2
# --------------------------------------
# Loss parameters
# --------------------------------------
loss_names: [mse, segment]
gamma: 0.8
w_seg: 1.0
w_rec: 1.0
# --------------------------------------
# Augmentation parameters
# --------------------------------------
# pipeline
multi_frame: true
remove_outliers: true
random_jitter: true
flip: false
normalize: true
random_scale: true
random_rotate: true
random_translate: true
reduce_keypoint_len: true
pad: true
gen_seg_gt: false
to_simple_coco: true
# parameters
clip_len: 7
outlier_type: 'box'
num_neighbors: 3
std_multiplier: 1.0
radius: 2.0
min_neighbors: 2
centroid_type: 'zonly'
num_frames: 3
jitter_std: 0.001
jitter_prob: 0.5
left_idxs: [5,6,7,11,12,13,15,17]
right_idxs: [2,3,4,8,9,10,14,16]
flip_prob: 0.5
feat_scale: null
scale_min: 0.9
scale_max: 1.1
scale_prob: 0.5
angle_min: -0.3141592653589793
angle_max: 0.3141592653589793
rotate_prob: 0.5
translate_range: 0.05
translate_prob: 0.5
only_one: true
keep_type: 'middle'
frame_to_reduce: 0
max_len: 1024
skeleton_type: 'mmfi'