strategy: ddp
benchmark: True
# skeleton_type: mmbody   # Set to "mmbody" or "coco" as needed
pretrained: False
sync_batchnorm: False
clip_grad: null
precision: 16
epochs: &epochs 100

# --------------------------------------
# Dataset parameters
# --------------------------------------
data_path: &data_path data/mmfi_lidar.pkl
train_dataset:
  name: TemporalDataset
  params:
    data_path: *data_path
    split: val_rdn_p3
val_dataset:
  name: TemporalDataset
  params:
    data_path: *data_path
    split: test_rdn_p3
test_dataset:
  name: TemporalDataset
  params:
    data_path: *data_path
    split: test_rdn_p3
predict_dataset:
  name: TemporalDataset
  params:
    data_path: data/mmfi_lidar.pkl
    split: test_rdn_p3
# --------------------------------------
# Optimizer parameters
# --------------------------------------
optim_name: AdamW
optim_params:
  lr: 0.00001
  weight_decay: 0.00001
  # momentum: 0.9

# --------------------------------------
# Learning rate scheduler parameters
# --------------------------------------
sched_name: LinearWarmupCosineAnnealingLR
sched_params:
  warmup_epochs: 20
  max_epochs: *epochs
  warmup_start_lr: 0.000001
  eta_min: 0.000001

# --------------------------------------
# Model parameters
# --------------------------------------
mode: train        # Add this line to your YAML file (for example, right after the sched_params or under the dataset section)
model_name: P4Transformer
model_params:
  radius: 0.7
  nsamples: 32
  spatial_stride: 8
  temporal_kernel_size: 3
  temporal_stride: 1
  emb_relu: false
  dim: 1024
  depth: 3
  heads: 8
  dim_head: 128
  mlp_dim: 2048
  output_dim: 39
  features: 0

# --------------------------------------
# Loss parameters
# --------------------------------------
loss_name: MSELoss
loss_params: null

# --------------------------------------
# Augmentation parameters
# --------------------------------------
train_pipeline:
  - name: UniformSample
    params:
      clip_len: 7
  - name: GetCentroidRadius
    params:
      centroid_type: 'zonly'
  - name: ToSimpleCOCO
    params: null
  - name: MultiFrameAggregate
    params:
      num_frames: 3
  - name: RemoveOutliers
    params:
      outlier_type: 'box'
      radius: 2.0
  - name: RandomJitter
    params:
      jitter_std: 0.001
    prob: 0.5
  # - name: Flip
  #   # Parameters are commented out because they are not needed currently, but might be useful in the future.
  #   params:
  #     left_idxs: [5,6,7,11,12]
  #     right_idxs: [2,3,4,8,9]
    # prob: 0.5
  - name: Normalize
    params:
      feat_scale: null
  - name: RandomScale
    params:
      scale_min: 0.9
      scale_max: 1.1
    prob: 0.5
  - name: RandomRotate
    params:
      angle_min: -3.141592653589793
      angle_max: 3.141592653589793
    prob: 0.5
  - name: RandomTranslate
    params:
      translate_range: 0.05
    prob: 0.5
  - name: ReduceKeypointLen
    params:
      only_one: true
      keep_type: 'middle'
      frame_to_reduce: 0
  - name: Pad
    params:
      max_len: 256
  - name: ToTensor
    params: null

val_pipeline: &val_pipeline
  - name: UniformSample
    params:
      clip_len: 7
  - name: GetCentroidRadius
    params:
      centroid_type: 'zonly'
  - name: ToSimpleCOCO
    params: null
  - name: MultiFrameAggregate
    params:
      num_frames: 3
  - name: RemoveOutliers
    params:
      outlier_type: 'box'
      radius: 2.0
  - name: Normalize
    params:
      feat_scale: null
  - name: ReduceKeypointLen
    params:
      only_one: true
      keep_type: 'middle'
      frame_to_reduce: 0
  - name: Pad
    params:
      max_len: 256
  - name: ToTensor
    params: null

test_pipeline: *val_pipeline

predict_pipeline: *val_pipeline
