strategy: ddp
benchmark: True
pretrained: False
sync_batchnorm: False
clip_grad: null
precision: 16
epochs: &epochs 100
# --------------------------------------
# Dataset parameters
# --------------------------------------
train_dataset:
  name: SklOnlyDataset
  params:
    data_path: &data_path data/lidarhuman26m.pkl
    split: [train, val]
val_dataset:
  name: SklOnlyDataset
  params:
    data_path: *data_path
    split: test
test_dataset:
  name: SklOnlyDataset
  params:
    data_path: data/mmfi.pkl
    split: test_rdn_p3
# --------------------------------------
# Optimizer parameters
# --------------------------------------
optim_name: AdamW
optim_params:
  lr: 0.0001
  weight_decay: 0.00001
# --------------------------------------
# Learning rate scheduler parameters
# --------------------------------------
sched_name: LinearWarmupCosineAnnealingLR
sched_params:
  warmup_epochs: 20
  max_epochs: *epochs
  warmup_start_lr: 0.00001
  eta_min: 0.00001
# --------------------------------------
# Model parameters
# --------------------------------------
mode: train
model_name: SpatialTemporalJointTransformer
model_params:
  seq_len: 30
  num_joints: 15
  depth: 3
  dim: 128
  heads: 8
  dim_head: 16
  mlp_dim: 256
  dropout: 0
# --------------------------------------
# Loss parameters
# --------------------------------------
loss_name: MSELoss
loss_params: null
# weight for auxiliary losses
w_loc: 1.0
w_flow: 1.0
# --------------------------------------
# Augmentation parameters
# --------------------------------------
train_pipeline:
  - name: UniformSample
    params:
      pad_type: 'start'
      clip_len: 31
  - name: ToITOP
    params: null
  - name: ToTensor
    params: null
val_pipeline: &val_pipeline
  - name: UniformSample
    params:
      pad_type: 'start'
      clip_len: 31
  - name: ToITOP
    params: null
  - name: ToTensor
    params: null
test_pipeline: *val_pipeline